# Generated by Django 3.2.25 on 2024-03-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=17)),
                ('insurance_date', models.DateField()),
                ('insurance_company', models.CharField(max_length=100)),
                ('policy_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('kilometers', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mileage',
            },
        ),
        migrations.CreateModel(
            name='StkEk',
            fields=[
                ('inspection_id', models.AutoField(primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=17)),
                ('inspection_date', models.DateField()),
                ('service_address', models.CharField(max_length=255)),
                ('inspection_type', models.CharField(max_length=10)),
                ('protocol', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vignette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('type', models.CharField(max_length=50)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
