# Generated by Django 3.2.25 on 2024-03-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='insurance',
            table='insurance',
        ),
        migrations.AlterModelTable(
            name='stkek',
            table='stk_ek',
        ),
        migrations.AlterModelTable(
            name='vignette',
            table='vignette',
        ),
    ]
